encoder_ip = "192.168.0.60"
encoder_port = 60003
em2rs_ip = "192.168.0.60"
em2rs_port = 60002
lir_id = 247
lir_step = 0.3515625
em2rs_id = 1
em2rs_low_limit = 2
em2rs_high_limit = 7
steps_per_mm = -27
