sensors_ip = "192.168.0.57"
sensors_port = 60002
em2rs_ip = "192.168.0.57"
em2rs_port = 60003

[slit_controller]
knife_trid_id = 3
water_trid_id = 4

[slit_controller.upper_axis]
lir_id = 247
lir_step = 0.0005
knife_trid_axis = 0
water_trid_axis = 0
em2rs_id = 1
em2rs_low_limit = 0
em2rs_high_limit = 100
steps_per_mm = 100

[slit_controller.lower_axis]
lir_id = 246
lir_step = 0.0005
knife_trid_axis = 1
water_trid_axis = 1
em2rs_id = 2
em2rs_low_limit = 0
em2rs_high_limit = 100
steps_per_mm = 100

[slit_controller.left_axis]
lir_id = 244
lir_step = 0.0005
knife_trid_axis = 2
water_trid_axis = 2
em2rs_id = 3
em2rs_low_limit = 0
em2rs_high_limit = 100
steps_per_mm = 100

[slit_controller.right_axis]
lir_id = 245
lir_step = 0.0005
knife_trid_axis = 3
water_trid_axis = 3
em2rs_id = 4
em2rs_low_limit = 0
em2rs_high_limit = 100
steps_per_mm = 100

[attenuator.axis]
lir_id = 243
lir_step = 0.0005
em2rs_id = 17
em2rs_low_limit = 2
em2rs_high_limit = 3
steps_per_mm = 5000

[collimator]
trid_id = 1

[collimator.input_axis]
trid_axis = 1

[collimator.output_axis]
trid_axis = 2

[water_input]
trid_id = 1

[water_input.axis]
trid_axis = 1
