sensors_ip = "192.168.0.57"
sensors_port = 60002
em2rs_ip = "192.168.0.57"
em2rs_port = 60003
icpcon_id = 1

[upper_axis]
lir_id = 247
lir_step = 0.0005
em2rs_id = 1
em2rs_low_limit = 3
em2rs_high_limit = 2
steps_per_mm = 9800

[lower_axis]
lir_id = 246
lir_step = 0.0005
em2rs_id = 2
em2rs_low_limit = 3
em2rs_high_limit = 2
steps_per_mm = 9800

[left_axis]
lir_id = 245
lir_step = 0.0005
em2rs_id = 3
em2rs_low_limit = 3
em2rs_high_limit = 2
steps_per_mm = 9800

[right_axis]
lir_id = 244
lir_step = 0.0005
em2rs_id = 4
em2rs_low_limit = 3
em2rs_high_limit = 2
steps_per_mm = 9800
