rf256_ip = "192.168.0.51"
rf256_port = 60002
trid_ip = "192.168.0.51"
trid_port = 60003
trid_device_id = 1

[upper_axis]
rf256_id = 9
trid_id = 1
standa_ip = "192.168.0.200"
standa_port = 2000
steps_per_mm = 800

[lower_axis]
rf256_id = 10
trid_id = 2
standa_ip = "192.168.0.200"
standa_port = 3000
steps_per_mm = 800

[right_axis]
rf256_id = 7
trid_id = 3
standa_ip = "192.168.0.201"
standa_port = 2000
steps_per_mm = 800

[left_axis]
rf256_id = 8
trid_id = 4
standa_ip = "192.168.0.201"
standa_port = 3000
steps_per_mm = 800
